# Generated by Django 2.1.7 on 2019-05-18 21:22

from django.db import migrations, models
import django.db.models.deletion
import restaurants.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0)),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('metroarea__metroarea_name', 'district_name'),
            },
        ),
        migrations.CreateModel(
            name='MetroArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metroarea_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(help_text='Remember to crop the image into a square!', upload_to=restaurants.models.picture_file_name)),
                ('caption', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(choices=[(1, '$'), (2, '$$'), (3, '$$$'), (4, '$$$$'), (5, '$$$$$'), (6, '$$$$$$')], default=1, help_text='$ = <10, $$ = 11-20, $$$ = 21-30, $$$$ = 31-50, $$$$$ = 51-100, $$$$$$ = >100')),
                ('address', models.CharField(max_length=300)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5)),
                ('positives', models.TextField(blank=True, default='', verbose_name='Positives')),
                ('negatives', models.TextField(blank=True, default='', verbose_name='Negatives')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('private_notes', models.TextField(blank=True, default='', verbose_name='Private Notes')),
                ('last_visit', models.DateField()),
                ('url_name', models.SlugField(unique=True)),
                ('cuisine', models.ManyToManyField(blank=True, to='restaurants.Cuisine')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.District')),
                ('metroarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.MetroArea')),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant'),
        ),
        migrations.AddField(
            model_name='district',
            name='metroarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.MetroArea'),
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant'),
        ),
    ]
