# Generated by Django 2.1.7 on 2019-12-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20190527_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='metroarea',
            name='address',
            field=models.CharField(default='Fremont, CA', max_length=100),
            preserve_default=False,
        ),
    ]
