# Generated by Django 2.1.7 on 2019-12-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_metroarea_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metroarea',
            name='address',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
