# Generated by Django 2.2.10 on 2022-01-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_auto_20190530_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cooking_time',
            new_name='active_time',
        ),
    ]
