# Generated by Django 4.2.11 on 2024-12-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_rename_is_experiment_recipe_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='number_of_attempts',
        ),
    ]
